name = "ticker-tracker"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "d6b4aa8e710d442d97e6c52b1027f92c"

[[kv_namespaces]]
binding = "ticker_tracker_kv"
id = "d6b4aa8e710d442d97e6c52b1027f92c"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
